version: '3.8'

services:
  # 应用服务（单一二进制文件，包含前端和后端）
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    environment:
      - PORT=8080
      - JWT_SECRET=your_jwt_secret_key
      - STORAGE_PATH=/app/storage
      - MAX_FILE_SIZE=104857600
      - MAX_ANONYMOUS_FILE_SIZE=52428800
      - DEFAULT_EXPIRE_HOURS=1
      - DEFAULT_DOWNLOAD_LIMIT=5
      - ADMIN_EMAIL=box@zaunist.com
      - ADMIN_PASSWORD=box123...
      - ADMIN_USERNAME=boxer
    restart: unless-stopped